# Generated by Django 2.0.7 on 2018-08-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
