# Generated by Django 2.0.7 on 2018-08-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_get_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='get_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
