# Generated by Django 2.0.7 on 2018-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rates',
            new_name='ratings',
        ),
        migrations.AlterField(
            model_name='rate',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
