# Generated by Django 2.0.7 on 2018-08-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180807_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='articles.Article'),
        ),
    ]
