# Generated by Django 2.0.7 on 2018-08-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180808_0715'),
        ('articles', '0005_auto_20180807_0927'),
    ]

    operations = [
    ]
