# Generated by Django 2.0.7 on 2018-08-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_merge_20180809_0730'),
        ('articles', '0003_merge_20180809_0711'),
    ]

    operations = [
    ]
