# Generated by Django 2.0.7 on 2018-08-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_parent'),
        ('articles', '0007_merge_20180809_1621'),
    ]

    operations = [
    ]
