# Generated by Django 2.0.7 on 2018-08-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180810_0438'),
        ('articles', '0008_merge_20180810_0725'),
    ]

    operations = [
    ]
